web:
  build: ./web
  command: ./node_modules/grunt-cli/bin/grunt serve:dist --force
  volumes:
    - .:/home/yeoman
  ports:
    - "9000:9000"
  links:
    - db
db:
  build: ./db
  volumes:
    - ./data/db:/db
  ports:
    - "27017"
    - "28017"

